package com.anton.elementalwands.crypt;

/**
 * Generated by art/hollow_crypt/build_layout.py: bough tops above the barrier lid where the
 * Necromancer stands during a siege. Block offsets from the clearing centre; y is the feet
 * height above {@link HollowCryptRealm#SURFACE_Y}.
 */
public final class HollowCryptPerches {
    private HollowCryptPerches() {}

    public static final int[][] SPOTS = {
        {-26, 37, -22},
        {-8, 37, -28},
        {22, 35, -26},
        {34, 34, -13},
        {31, 43, 8},
        {18, 34, 24},
        {0, 37, 32},
        {-30, 37, 16},
    };
}
