import{Mesh,createRenderer,add,mix,mul,clamp,smooth,rnd,TAU,C}from'./engine.js';
import{floor,roots,plant,seedPod,flower,rootTile,elderTree,player,spider,guardian,wrap}from'./models.js';
const $=id=>document.getElementById(id), canvas=$('view');let renderer;
try{renderer=createRenderer(canvas)}catch(e){$('error').hidden=false;$('error').textContent=e.message;throw e}
const info={
 seed:{kicker:'PRIMARY / SEED & SEEDLING',title:'Small beginnings. Living roots.',label:'SEED → IMPACT → SPROUT → BLOOM',duration:9,distance:4.8,target:[0,.70,0],desc:'A chunky seed pod unfolds into a vivid green anchor. Stepped leaves and thick pink petals frame a golden center, with violet accents beneath the flower.',detail:'Scrub from the start to see the winged seed arrive. The curled bud opens as the plant matures. Small side blooms appear last.',phase:t=>t<1.3?'Winged seed':t<2?'Taking root':t<5?'Unfurling':t<7?'Mature plant':'Ready bloom'},
 field:{kicker:'PRIMARY / TERRITORY',title:'The ground begins to answer.',label:'LOW ROOTS / RAISED THORNS / CLEAR TERRITORY',duration:9,distance:10,target:[0,.05,0],desc:'Interwoven roots spread in readable bands, carrying raised thorns and occasional flowers. The effect stays low enough to see creatures moving through it.',detail:'Land uses woody roots and thorns. Water uses overlapping leaves held by a woven root rim, with a small blossom at the center.',phase:t=>t<2?'First roots':t<5?'Spreading':'Established thicket'},
 bloom:{kicker:'SECONDARY / REACHING VINES',title:'One flower. Vines do the reaching.',label:'TRAIL → REACH THE TARGET → CLIMB',duration:8,distance:9.0,target:[0,.65,0],desc:'The original flower stays the only floral anchor. Paired green vines follow a stepped path to the enemy, then climb and grip its body. No second flower appears.',detail:'The low trail leads the eye from the flower to the target. Straight vine segments turn at angular joints, and small leaves appear along the climb.',phase:t=>t<2.8?'Vines reaching':t<5.4?'Climbing the target':'Vines attached'},
 tree:{kicker:'ULTIMATE / BLOCK-BUILT OVERGROWTH',title:'A Minecraft tree. A living heart.',label:'OAK LOGS → BRANCHES → LEAF CANOPY → CUSTOM ACCENTS',duration:10,distance:24,target:[0,3.7,0],desc:'The same nine-block height, with longer horizontal limbs and separate leafy crowns spreading eleven blocks across. Actual Minecraft oak textures give the trunk and leaves their familiar character.',detail:'Two custom accents: one heartwood block in the trunk, and a few flowering oak-leaf blocks. The rest is ordinary oak. Every structural block stays one block in size.',phase:t=>t<2?'Oak trunk forming':t<4?'Branches growing':t<7?'Leaf blocks spreading':'Heartwood & flowering oak'},
 entangle:{kicker:'STATUS / ENTANGLE',title:'You can see the hold tighten.',label:'FOLLOWING VINES / VISIBLE STACKS / HONEST STATES',duration:12,distance:6.7,target:[0,.85,0],desc:'Vines stay attached to the target. Each stack adds an angular climbing strand and more thorns. A rooted target gains a distinct clasp reaching from the feet into the ground.',detail:'The Guardian keeps moving: strained vines signal pressure. An earned opening uses a brief firm clasp and bright sap nodes; resistance has loose, flexing roots.',phase:t=>'Entangle'}
};
let state={scene:'seed',time:6.3,playing:false,speed:1,orbit:true,night:false,subject:'player',stacks:3,mode:'rooted',surface:'land',manual:false};
let camera={yaw:.60,pitch:.26,distance:6.6,target:[0,.65,0]},modelData=null;
fetch('guardian.json').then(r=>{if(!r.ok)throw Error('Guardian reference could not load');return r.json()}).then(x=>{modelData=x}).catch(e=>{console.error(e);$('saved').textContent=e.message});
function setScene(name){state.scene=name;state.manual=false;state.time=info[name].duration*.74;state.playing=false;$('play').textContent='▶';$('play').setAttribute('aria-label','Play animation');for(let b of document.querySelectorAll('.scene')){b.classList.toggle('active',b.dataset.scene===name);b.setAttribute('aria-current',b.dataset.scene===name?'true':'false')}let i=info[name];$('kicker').textContent=i.kicker;$('title').textContent=i.title;$('scene-label').textContent=i.label;$('description').textContent=i.desc;$('detail').textContent=i.detail;$('timeline').max=i.duration;$('entangle-options').hidden=name!=='entangle';$('field-options').hidden=name!=='field';$('timeline-label').textContent=name==='entangle'?'Build stacks → root → release':name==='tree'?'Ultimate awakening':'Cast & growth';resetCamera();if(name==='entangle'){state.manual=true;state.stacks=3}document.title=`Nature · ${i.title}`;updateControls()}
function resetCamera(){let i=info[state.scene];camera.distance=i.distance;camera.target=[...i.target];camera.yaw=.60;camera.pitch=state.scene==='field'?.62:.26;if(state.scene==='entangle')subjectCamera()}
function subjectCamera(){if(state.subject==='guardian'){camera.distance=17;camera.target=[0,2.4,0]}else if(state.subject==='spider'){camera.distance=7;camera.target=[0,.35,0];camera.pitch=.45}else{camera.distance=6.7;camera.target=[0,.85,0];camera.pitch=.22}}
for(let b of document.querySelectorAll('.scene'))b.onclick=()=>setScene(b.dataset.scene);
$('lighting').onclick=()=>{state.night=!state.night;document.body.classList.toggle('night',state.night);$('lighting').textContent=state.night?'☾ Dusk':'☀ Daylight'};
$('play').onclick=()=>{state.playing=!state.playing;state.manual=false;$('play').textContent=state.playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',state.playing?'Pause animation':'Play animation')};
$('restart').onclick=()=>{state.time=0;state.playing=true;state.manual=false;$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','Pause animation')};
$('timeline').oninput=()=>{state.time=+$('timeline').value;state.playing=false;state.manual=false;$('play').textContent='▶';$('play').setAttribute('aria-label','Play animation')};
$('speed').onclick=()=>{state.speed=state.speed===1?.5:state.speed===.5?1.5:1;$('speed').textContent=state.speed+'×'};
$('orbit').onclick=()=>{state.orbit=!state.orbit;$('orbit').classList.toggle('selected',state.orbit)};
$('front').onclick=()=>{camera.yaw=0;camera.pitch=state.scene==='field'?.70:.1;state.orbit=false;$('orbit').classList.remove('selected')};$('reset').onclick=resetCamera;
$('target').onchange=()=>{state.subject=$('target').value;subjectCamera();if(state.subject==='guardian'&&state.mode==='rooted'){state.mode='resisting';$('root-state').value='resisting'}if(state.subject!=='guardian'&&['opening','resisting'].includes(state.mode)){state.mode='rooted';$('root-state').value='rooted'}updateControls()};
$('surface').onchange=()=>state.surface=$('surface').value;
for(let b of $('stacks').children)b.onclick=()=>{state.stacks=+b.dataset.stack;state.manual=true;state.playing=false;$('play').textContent='▶';updateControls()};
$('root-state').onchange=()=>{state.mode=$('root-state').value;state.stacks=5;state.manual=true;state.playing=false;$('play').textContent='▶';if(['opening','resisting'].includes(state.mode)&&state.subject!=='guardian'){state.subject='guardian';$('target').value='guardian';subjectCamera()}updateControls()};
const modes={rooted:'Root active',lingering:'Stacks linger · root ended',opening:'Opening earned',resisting:'Boss resistance'};
function entangleState(){if(state.manual)return{stacks:state.stacks,mode:state.subject==='guardian'&&state.mode==='rooted'?'resisting':state.mode};let t=state.time,stacks=t<1?0:t<6?Math.ceil(t-1):5,mode=t<9?'rooted':'lingering';if(state.subject==='guardian')mode=t<7?'resisting':t<9?'opening':'resisting';return{stacks:Math.min(5,stacks),mode}}
function updateControls(){let e=entangleState();for(let b of $('stacks').children)b.classList.toggle('selected',+b.dataset.stack===e.stacks);$('time').textContent=`${state.time.toFixed(1)} / ${info[state.scene].duration.toFixed(1)} s`;$('timeline').value=state.time;$('phase').textContent=state.scene==='entangle'?`${e.stacks} / 5 · ${e.stacks<5?(e.stacks?'Slowing':'Unbound'):modes[e.mode]}`:info[state.scene].phase(state.time);if(state.scene==='entangle')$('scale').textContent=state.subject==='guardian'?'EXISTING GUARDIAN GEOMETRY · PROPOSED VINE ANIMATION':'TARGET SCALE REFERENCE · 1 BLOCK GRID';else $('scale').textContent='GROUND GRID: 1 MINECRAFT BLOCK'}
let drag=false,px=0,py=0;
canvas.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId);state.orbit=false;$('orbit').classList.remove('selected')};canvas.onpointermove=e=>{if(!drag)return;camera.yaw-=(e.clientX-px)*.008;camera.pitch=clamp(camera.pitch+(e.clientY-py)*.006,-.06,1.35);px=e.clientX;py=e.clientY};canvas.onpointerup=canvas.onpointercancel=()=>drag=false;canvas.addEventListener('wheel',e=>{e.preventDefault();camera.distance=clamp(camera.distance*Math.exp(e.deltaY*.001),2.1,35)},{passive:false});
let storeKey='elementalwands-nature-workshop-feedback';try{$('notes').value=localStorage.getItem(storeKey)||''}catch{}$('notes').oninput=()=>{try{localStorage.setItem(storeKey,$('notes').value);$('saved').textContent='Saved locally'}catch{$('saved').textContent='Notes are available until this tab closes'}};$('copy').onclick=async()=>{let text=`Nature preview — ${info[state.scene].title}\n${$('notes').value}`;try{await navigator.clipboard.writeText(text);$('saved').textContent='Copied — paste your feedback into the task'}catch{$('notes').select();$('saved').textContent='Select and copy the notes above'}};
function sceneMesh(t,ambient){let m=new Mesh();switch(state.scene){case'seed':{floor(m,3);let g=smooth((t-1.35)/4.7);if(t<1.35){let u=smooth(t/1.35);seedPod(m,[-2.4*(1-u),.25+1.6*(1-u),.1],.60,ambient*2)}if(t>=1.2)plant(m,[0,.02,0],Math.max(.035,g),ambient);break}
case'field':{floor(m,4,state.surface==='water');let r=clamp(t/1.5,0,3);for(let x=-2;x<=2;x++)for(let z=-2;z<=2;z++){let dist=Math.max(Math.abs(x),Math.abs(z)),g=smooth((r-dist)*1.7);if(g>0)rootTile(m,[x,.015,z],g,x*17+z*13+8,state.surface==='water',ambient)}if(state.surface==='land')plant(m,[0,.01,0],.85,ambient);break}
case'bloom':{
 floor(m,4);plant(m,[-2.2,.01,0],.85,ambient);player(m,[1.8,0,0],ambient);
 let reach=smooth(t/2.8),path=[[-2.2,.065,0],[-1.6,.065,0],[-1.6,.065,.18],[-.55,.065,.18],[-.55,.065,-.10],[.65,.065,-.10],[.65,.065,.12],[1.8,.065,.12]];
 for(let side of[-1,1]){
  let n=reach*(path.length-1),index=Math.floor(n),pts=path.slice(0,index+1).map(p=>add(p,[0,0,side*.10]));
  if(index<path.length-1)pts.push(add(mix(path[index],path[index+1],n-index),[0,0,side*.10]));
  m.tube(pts,.055,side===1?C.root:C.leaf,1,4,.033);
  for(let i=1;i<pts.length;i+=2){let p=pts[i];m.leaf(p,add(p,[.12,.14,side*.26]),.095,C.lightleaf)}
 }
 if(t>2.6){let g=smooth((t-2.6)/2.8);m.at([1.8,0,0],()=>wrap(m,.60,1.8,3,'lingering',ambient,false,g))}
 break}

case'tree':{floor(m,6);elderTree(m,[0,.02,0],smooth(t/8),ambient);player(m,[4.5,0,3.6],ambient);break}
case'entangle':{let e=entangleState(),boss=state.subject==='guardian';floor(m,boss?5:3);if(boss)guardian(m,modelData,ambient,e.mode==='opening');else if(state.subject==='spider')spider(m,[0,0,0],ambient);else player(m,[0,0,0],ambient);wrap(m,boss?3.35:state.subject==='spider'?1.65:.60,boss?5.2:state.subject==='spider'?.66:1.8,e.stacks,e.mode,ambient,boss);break}}
return m}
let last=performance.now(),lastDraw=0;window.__naturePreview={state,camera,setScene,sceneMesh,renderer};
function frame(now){let dt=Math.min(.08,(now-last)/1000);last=now;if(state.playing)state.time=(state.time+dt*state.speed)%info[state.scene].duration;if(state.orbit&&!drag)camera.yaw+=dt*.12;if(now-lastDraw>1000/30){lastDraw=now;let m=sceneMesh(state.time,now/1000);renderer.draw(m,camera,state.night);updateControls();window.__naturePreview.triangles=m.triangles}requestAnimationFrame(frame)}
setScene('seed');requestAnimationFrame(frame);
