"""Bake the approved throwing hand's socket into a tiny server-side pose table."""
import argparse
import runpy
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
pose = runpy.run_path(str(ROOT / 'art/fractured_guardian/v4-expressive/preview_motion.py'))
np = pose['np']
clip = pose['clips']['animation.fractured_guardian.throw']
# Center of the palm grip, in the source model's 16-units-per-block coordinates.
socket = np.array([-34., 3., -22., 1.])
rows = []
for tick in range(45):
    value = (pose['matrices'](clip, tick / 20)['right_hand'] @ socket)[:3] / 16
    rows.append('        {' + ', '.join(f'{v:.6f}' for v in value) + '}')
source = '''package com.anton.elementalwands.entity;

import net.minecraft.util.math.Vec3d;

/** Generated by tools/prepare_guardian_throw_socket.py from the approved V4 rig. */
final class GuardianThrowSocket {
    private static final double[][] POSES = {
''' + ',\n'.join(rows) + '''
    };

    static Vec3d worldPosition(FracturedGuardianEntity guardian, int tick) {
        return guardian.getEntityPos().add(worldOffset(guardian.getYaw(), tick));
    }

    static Vec3d worldOffset(float degrees, int tick) {
        double[] p = POSES[Math.clamp(tick, 0, POSES.length-1)];
        double yaw = Math.toRadians(degrees);
        // GeckoLib mirrors source X, then rotates by 180 - bodyYaw.
        return new Vec3d(p[0]*Math.cos(yaw)+p[2]*Math.sin(yaw), p[1],
                p[0]*Math.sin(yaw)-p[2]*Math.cos(yaw));
    }
}
'''
target = ROOT / 'src/main/java/com/anton/elementalwands/entity/GuardianThrowSocket.java'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if args.check:
    assert target.read_text() == source, 'Throw socket has drifted from the animation source'
else:
    target.write_text(source)
print('Guardian throw socket: 45 sampled hand positions verified.')
