package com.anton.elementalwands.entity.undead;

/** Generated by art/hollow_necromancer/undead/build_runtime.py from the installed clips; do not edit. */
public final class HollowUndeadClips {
    /** Crawler: clip lengths in ticks, 1x walk speed in blocks/s, hit tick and socket (blocks: right, up, forward). */
    public static final int CRAWLER_RISE = 38, CRAWLER_ATTACK = 28, CRAWLER_DEATH = 32, CRAWLER_HIT = 12;
    public static final double CRAWLER_STRIDE = 0.1250;
    public static final double[] CRAWLER_SOCKET = {0.234, 0.069, 0.941};

    /** Archer: clip lengths in ticks, 1x walk speed in blocks/s, hit tick and socket (blocks: right, up, forward). */
    public static final int ARCHER_RISE = 72, ARCHER_ATTACK = 80, ARCHER_DEATH = 34, ARCHER_HIT = 52;
    public static final double ARCHER_STRIDE = 0.1562;
    public static final double[] ARCHER_SOCKET = {-0.850, 1.562, 0.200};

    /** Brute: clip lengths in ticks, 1x walk speed in blocks/s, hit tick and socket (blocks: right, up, forward). */
    public static final int BRUTE_RISE = 72, BRUTE_ATTACK = 92, BRUTE_DEATH = 34, BRUTE_HIT = 43;
    public static final double BRUTE_STRIDE = 0.1389;
    public static final double[] BRUTE_SOCKET = {0.630, 1.054, 1.843};

    private HollowUndeadClips() {}
}
